#!/bin/bash -x
python3 -m pytest tests
version=$1
echo $version >VERSION
echo "__version__ = '$version'" >ped_core/version.py
file_version=${version//[\.]/_}
if [ -f ped_$file_version.zip ];
    then rm ped_$file_version.zip;
fi
./mkdocs
zip_python () {
    if [ -d $1 ];
         then return;
    elif [[ $1 == *.py ]];
        then zip -q ped_$2.zip $1;
    elif [ `grep -c "\#\!.*python" $1` -eq 1 ];
        then zip -q ped_$2.zip $1;
    fi
}
for f in {ped_core,ped_dialog,ped_ssh_dialog,ped_extensions,scripts}/*;
do zip_python $f $file_version;
done
zip -q ped_$file_version.zip docs/*
for f in docs/{ped_core,ped_dialog,ped_ssh_dialog,ped_extensions,scripts}/*;
do zip -q ped_$file_version.zip $f;
done
zip -q ped_$file_version.zip requirements.txt
zip -q ped_$file_version.zip LICENSE
zip -q ped_$file_version.zip README.md
unzip -l ped_$file_version.zip
if [ -d dist ];
    then rm -rf dist
fi
if [ -d build ];
    then rm -rf build
fi
python3 -m pip install --upgrade setuptools wheel
python3 setup.py sdist bdist_wheel
