#!/bin/bash
OLDPYTHONPATH=$PYTHONPATH
export PYTHONPATH="."
coverage run --source=. --omit=bin/*,lib/*,tests/* -m pytest tests "$@"
set status=${PIPESTATUS[0]}
coverage report
export PYTHONPATH=$OLDPYTHONPATH
exit $status
